version: "3.9"
services:
  redis:
    ports:
      - "6379:6379"
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
  mongo:
    ports:
      - 27017:27017
  mongo-express:
    ports:
      - 8081:8081
